name: Cache Azure Login

description: Login to Azure and Cache Credentials

inputs:
  azureCredentials:
    description: "Credentials to login to Azure"
    required: true

branding:
  color: blue
  icon: log-in

runs:
  using: "composite"
  steps:
    - name: Hash azureCredentials secret
      id: hash
      shell: bash
      run: |
        echo "azure-credentials-hash=$(echo ${{ inputs.azureCredentials }} | md5sum - | awk '{print $1}')" >> $GITHUB_OUTPUT

    - name: Cache Azure credentials
      id: azure-cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.Azure
          ${{ github.workspace }}/.Azure
        key: ${{ runner.os }}-azurecreds-${{ steps.hash.outputs.azure-credentials-hash }}

    - name: Login via Az module
      if: steps.azure-cache.outputs.cache-hit != 'true'
      uses: azure/login@v1
      with:
        creds: "${{ inputs.azureCredentials }}"
        enable-AzPSSession: true
