name: Cache Azure Login

description: Login to Azure and Cache Credentials

inputs:
  azureCredentials:
    description: "Credentials to login to Azure"
    required: true
  enable-AzPsSession:
    description: "Enable Azure PS Session"
    required: false

branding:
  color: blue
  icon: log-in

runs:
  using: "composite"
  steps:
    - name: Hash azureCredentials secret
      id: hash
      shell: bash
      run: |
        AZURE_CREDENTIALS="${{ inputs.azureCredentials }}"
        AZURE_CREDENTIALS_HASH=$(echo "${AZURE_CREDENTIALS}" | md5sum - | awk '{print $1}')
        echo "azure-credentials-hash=${AZURE_CREDENTIALS_HASH}" >> $GITHUB_OUTPUT

    - name: Cache Azure credentials
      id: azure-cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.Azure
          ~/.azure
          ${{ github.workspace }}/.Azure
          ${{ github.workspace }}/.azure
        key: ${{ runner.os }}-azurecreds-${{ steps.hash.outputs.azure-credentials-hash }}

    - name: Login via Az module
      if: steps.azure-cache.outputs.cache-hit != 'true'
      uses: azure/login@v1
      with:
        creds: "${{ inputs.azureCredentials }}"
        enable-AzPSSession: ${{ inputs.enable-AzPsSession || true }}
